import type { Metadata } from "next";
import { ToggleThemeButton } from "@/components/shared";
import { MoveLeft } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Client-side Rendering (CSR)",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex justify-center w-full min-h-screen bg-white dark:bg-[#0e0f11]">
      <div className="w-[567px] h-[513px] border-none shadow-none relative bg-white dark:bg-[#0e0f11]">
        <div className="flex justify-between items-center">
          <Link href="/">
            {" "}
            <MoveLeft
              className="absolute hover:bg-transparent top-6 left-0 text-[#0e0f11] dark:text-white"
              size={21}
            />
          </Link>
          <ToggleThemeButton />
        </div>
        {children}
      </div>
    </main>
  );
}
